name: Deploy to OpenShift via Tekton

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OpenShift CLI (oc)
        run: |
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz | tar -xz
          sudo mv oc /usr/local/bin/
          chmod +x /usr/local/bin/oc

      - name: Login to OpenShift
        run: |
          oc login ${{ secrets.OPENSHIFT_API_URL }} --token=${{ secrets.OPENSHIFT_TOKEN }} --insecure-skip-tls-verify

      - name: Install Tekton CLI (tkn) from OpenShift
        run: |
          curl -LO https://tkn-cli-serve-tekton-pipelines.apps.rm2.thpm.p1.openshiftapps.com/tkn/tkn-linux-amd64.tar.gz
          tar -xvzf tkn-linux-amd64.tar.gz
          sudo mv tkn /usr/local/bin/
          chmod +x /usr/local/bin/tkn

      - name: Verify Tekton CLI Installation
        run: |
          tkn version

      - name: Start Tekton Pipeline
        run: |
          tkn pipeline start new-pipeline -n jiminbyun-dev
